module.exports.proxy_paths = [
  "systems",
  "modules",
  "fonts",
  "icons",
  "css",
  "ui",
  "worlds",
  "token-action-hud-core",
  "pdftofoundry",
  "helyx",
  "tokenizer",
  "pdftofoundry-image-mapping.json",
  "DigDownCache.json",
  "forge-assets.json",
  "adventures",
  "ddb-images",
  "moulinette",
  "Tokens",
  "Pawns",
  "Maps",
  "Modular",
  "FA_Animations_01",
  "FA_Mapmaking_Pack",
  "nameforge-models",
  "oif",
  "PDF",
  "Rime of The Frostmaiden",
  "891131-The_Streets_of_Bryn_Shandler_GRIDOFF.jpg",
  "BAC0X-portrait.jpg",
  "Daniel-Radcliffe-2022-London-England.webp",
  "Icewind Dale Large.jpg",
  "orhQI8-TopView.jpg",
  "orhQI8-TopView.webp",
  "sharp_eye_lakurr_ra.Token6lZlt7LkvTUDJxLG.webp",
  "sharpeye.jpg",
  "three flags sailing.jpg",
  "tp7ethujq5n71.webp",
  "wed_halfling_alias_av.jpg",
];
